# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98dec81ef3be6f726e7a7acb1d820d0c15c9ca5471175ac5e2b301f70384c4d7a857d7a0f4f8081d933da5ff00fd1370ea2a1767102ce1dafe145ca8d1a614b5

test:
  secret_key_base: 004ae73f6d02b839b9b9ad53d56bf0c512f75a116ce24b6a8b227d8ee8a1173d67f209567af9a12e29c623a3da17c3443901d046a5a228f5772cc791fa08b6ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
